#include <X11/Xutil.h>
#include <X11/XF86keysym.h>


typedef struct {
    const char* name;
    int key;
} KeyNames;


enum _MMKeyCode {
    K_NOT_A_KEY = 9999,

    K_BACKSPACE = XK_BackSpace,
    K_DELETE = XK_Delete,
    K_RETURN = XK_Return,
    K_TAB = XK_Tab,
    K_ESCAPE = XK_Escape,

    K_UP = XK_Up,
    K_DOWN = XK_Down,
    K_RIGHT = XK_Right,
    K_LEFT = XK_Left,

    K_HOME = XK_Home,
    K_END = XK_End,
    K_PAGEUP = XK_Page_Up,
    K_PAGEDOWN = XK_Page_Down,

    K_F1 = XK_F1,
    K_F2 = XK_F2,
    K_F3 = XK_F3,
    K_F4 = XK_F4,
    K_F5 = XK_F5,
    K_F6 = XK_F6,
    K_F7 = XK_F7,
    K_F8 = XK_F8,
    K_F9 = XK_F9,
    K_F10 = XK_F10,
    K_F11 = XK_F11,
    K_F12 = XK_F12,
    K_F13 = XK_F13,
    K_F14 = XK_F14,
    K_F15 = XK_F15,
    K_F16 = XK_F16,
    K_F17 = XK_F17,
    K_F18 = XK_F18,
    K_F19 = XK_F19,
    K_F20 = XK_F20,
    K_F21 = XK_F21,
    K_F22 = XK_F22,
    K_F23 = XK_F23,
    K_F24 = XK_F24,

    K_A = XK_A,
    K_B = XK_B,
    K_C = XK_C,
    K_D = XK_D,
    K_E = XK_E,
    K_F = XK_F,
    K_G = XK_G,
    K_H = XK_H,
    K_I = XK_I,
    K_J = XK_J,
    K_K = XK_K,
    K_L = XK_L,
    K_M = XK_M,
    K_N = XK_N,
    K_O = XK_O,
    K_P = XK_P,
    K_Q = XK_Q,
    K_R = XK_R,
    K_S = XK_S,
    K_T = XK_T,
    K_U = XK_U,
    K_V = XK_V,
    K_W = XK_W,
    K_X = XK_X,
    K_Y = XK_Y,
    K_Z = XK_Z,

    K_COMMA = XK_comma,
    K_PERIOD = XK_period,
    K_SLASH = XK_slash,

    K_SEMICOLON = XK_semicolon,
    K_QUOTE = XK_apostrophe,
    K_LEFTBRACKET = XK_bracketleft,
    K_RIGHTBRACKET = XK_bracketright,
    K_BACKSLASH = XK_backslash,

    K_MINUS = XK_minus,
    K_EQUAL = XK_equal,

    K_GRAVE = XK_grave,

    K_META = XK_Super_L,
    K_RIGHTMETA = XK_Super_R,

    K_CMD = K_NOT_A_KEY,
    K_RIGHTCMD = K_NOT_A_KEY,

    K_WIN = XK_Super_L,
    K_RIGHTWIN = XK_Super_R,

    K_ALT = XK_Alt_L,
    K_RIGHTALT = XK_Alt_R,

    K_FUNCTION = K_NOT_A_KEY,
    K_PAUSE = XK_Pause,

    K_CONTROL = XK_Control_L,
    K_RIGHTCONTROL = XK_Control_R,

    K_SHIFT = XK_Shift_L,
    K_RIGHTSHIFT = XK_Shift_R,

    K_CAPSLOCK = XK_Caps_Lock,
    K_NUMLOCK = XK_Num_Lock,
    K_SCROLL_LOCK = XK_Scroll_Lock,

    K_SPACE = XK_space,
    K_INSERT = XK_Insert,
    K_PRINTSCREEN = XK_Print,
    K_MENU = K_NOT_A_KEY,

    K_ADD = XK_KP_Add,
    K_SUBTRACT = XK_KP_Subtract,
    K_DIVIDE = XK_KP_Divide,
    K_MULTIPLY = XK_KP_Multiply,
    K_ENTER = XK_KP_Enter,
    K_CLEAR = XK_Clear,

    K_0 = XK_0,
    K_1 = XK_1,
    K_2 = XK_2,
    K_3 = XK_3,
    K_4 = XK_4,
    K_5 = XK_5,
    K_6 = XK_6,
    K_7 = XK_7,
    K_8 = XK_8,
    K_9 = XK_9,

    K_NUMPAD_0 = XK_KP_0,
    K_NUMPAD_1 = XK_KP_1,
    K_NUMPAD_2 = XK_KP_2,
    K_NUMPAD_3 = XK_KP_3,
    K_NUMPAD_4 = XK_KP_4,
    K_NUMPAD_5 = XK_KP_5,
    K_NUMPAD_6 = XK_KP_6,
    K_NUMPAD_7 = XK_KP_7,
    K_NUMPAD_8 = XK_KP_8,
    K_NUMPAD_9 = XK_KP_9,
    K_NUMPAD_DECIMAL = XK_KP_Decimal,

    K_AUDIO_VOLUME_DOWN = XF86XK_AudioLowerVolume,
    K_AUDIO_VOLUME_UP = XF86XK_AudioRaiseVolume,
    K_AUDIO_VOLUME_MUTE = XF86XK_AudioMute,
    K_AUDIO_PLAY = XF86XK_AudioPlay,
    K_AUDIO_STOP = XF86XK_AudioStop,
    K_AUDIO_PAUSE = XF86XK_AudioPause,
    K_AUDIO_PREV = XF86XK_AudioPrev,
    K_AUDIO_NEXT = XF86XK_AudioNext,
    K_AUDIO_REWIND = XF86XK_AudioRewind,
    K_AUDIO_FORWARD = XF86XK_AudioForward,
    K_AUDIO_REPEAT = XF86XK_AudioRepeat,
    K_AUDIO_RANDOM = XF86XK_AudioRandomPlay,

    K_LIGHTS_MON_DOWN = XF86XK_MonBrightnessDown,
    K_LIGHTS_MON_UP = XF86XK_MonBrightnessUp,
    K_LIGHTS_KBD_TOGGLE = XF86XK_KbdLightOnOff,
    K_LIGHTS_KBD_DOWN = XF86XK_KbdBrightnessDown,
    K_LIGHTS_KBD_UP = XF86XK_KbdBrightnessUp
};

static KeyNames key_names[] =
        {
                {"backspace",         K_BACKSPACE},
                {"delete",            K_DELETE},
                {"return",            K_RETURN},
                {"tab",               K_TAB},
                {"escape",            K_ESCAPE},

                {"up",                K_UP},
                {"down",              K_DOWN},
                {"right",             K_RIGHT},
                {"left",              K_LEFT},

                {"home",              K_HOME},
                {"end",               K_END},
                {"pageup",            K_PAGEUP},
                {"pagedown",          K_PAGEDOWN},

                {"0",                 K_0},
                {"1",                 K_1},
                {"2",                 K_2},
                {"3",                 K_3},
                {"4",                 K_4},
                {"5",                 K_5},
                {"6",                 K_6},
                {"7",                 K_7},
                {"8",                 K_8},
                {"9",                 K_9},

                {"a",                 K_A},
                {"b",                 K_B},
                {"c",                 K_C},
                {"d",                 K_D},
                {"e",                 K_E},
                {"f",                 K_F},
                {"g",                 K_G},
                {"h",                 K_H},
                {"i",                 K_I},
                {"j",                 K_J},
                {"k",                 K_K},
                {"l",                 K_L},
                {"m",                 K_M},
                {"n",                 K_N},
                {"o",                 K_O},
                {"p",                 K_P},
                {"q",                 K_Q},
                {"r",                 K_R},
                {"s",                 K_S},
                {"t",                 K_T},
                {"u",                 K_U},
                {"v",                 K_V},
                {"w",                 K_W},
                {"x",                 K_X},
                {"y",                 K_Y},
                {"z",                 K_Z},

                {",",                 K_COMMA},
                {".",                 K_PERIOD},
                {"/",                 K_SLASH},

                {";",                 K_SEMICOLON},
                {"'",                 K_QUOTE},
                {"[",                 K_LEFTBRACKET},
                {"]",                 K_RIGHTBRACKET},
                {"\\",                K_BACKSLASH},

                {"-",                 K_MINUS},
                {"=",                 K_EQUAL},

                {"`",                 K_GRAVE},

                {"f1",                K_F1},
                {"f2",                K_F2},
                {"f3",                K_F3},
                {"f4",                K_F4},
                {"f5",                K_F5},
                {"f6",                K_F6},
                {"f7",                K_F7},
                {"f8",                K_F8},
                {"f9",                K_F9},
                {"f10",               K_F10},
                {"f11",               K_F11},
                {"f12",               K_F12},
                {"f13",               K_F13},
                {"f14",               K_F14},
                {"f15",               K_F15},
                {"f16",               K_F16},
                {"f17",               K_F17},
                {"f18",               K_F18},
                {"f19",               K_F19},
                {"f20",               K_F20},
                {"f21",               K_F21},
                {"f22",               K_F22},
                {"f23",               K_F23},
                {"f24",               K_F24},

                {"meta",              K_META},
                {"right_meta",        K_RIGHTMETA},

                {"cmd",               K_CMD},
                {"right_cmd",         K_RIGHTCMD},

                {"win",               K_WIN},
                {"right_win",         K_RIGHTWIN},

                {"alt",               K_ALT},
                {"right_alt",         K_RIGHTALT},

                {"control",           K_CONTROL},
                {"right_control",     K_RIGHTCONTROL},

                {"shift",             K_SHIFT},
                {"right_shift",       K_RIGHTSHIFT},

                {"space",             K_SPACE},

                {"printscreen",       K_PRINTSCREEN},
                {"insert",            K_INSERT},
                {"menu",              K_MENU},
                {"fn",                K_FUNCTION},
                {"pause",             K_PAUSE},

                {"caps_lock",         K_CAPSLOCK},
                {"num_lock",          K_NUMLOCK},
                {"scroll_lock",       K_SCROLL_LOCK},

                {"audio_mute",        K_AUDIO_VOLUME_MUTE},
                {"audio_vol_down",    K_AUDIO_VOLUME_DOWN},
                {"audio_vol_up",      K_AUDIO_VOLUME_UP},
                {"audio_play",        K_AUDIO_PLAY},
                {"audio_stop",        K_AUDIO_STOP},
                {"audio_pause",       K_AUDIO_PAUSE},
                {"audio_prev",        K_AUDIO_PREV},
                {"audio_next",        K_AUDIO_NEXT},
                {"audio_rewind",      K_AUDIO_REWIND},
                {"audio_forward",     K_AUDIO_FORWARD},
                {"audio_repeat",      K_AUDIO_REPEAT},
                {"audio_random",      K_AUDIO_RANDOM},

                {"numpad_0",          K_NUMPAD_0},
                {"numpad_1",          K_NUMPAD_1},
                {"numpad_2",          K_NUMPAD_2},
                {"numpad_3",          K_NUMPAD_3},
                {"numpad_4",          K_NUMPAD_4},
                {"numpad_5",          K_NUMPAD_5},
                {"numpad_6",          K_NUMPAD_6},
                {"numpad_7",          K_NUMPAD_7},
                {"numpad_8",          K_NUMPAD_8},
                {"numpad_9",          K_NUMPAD_9},
                {"numpad_decimal",    K_NUMPAD_DECIMAL},
                {"enter",             K_ENTER},
                {"clear",             K_CLEAR},

                {"add",               K_ADD},
                {"subtract",          K_SUBTRACT},
                {"multiply",          K_MULTIPLY},
                {"divide",            K_DIVIDE},

                {"lights_mon_up",     K_LIGHTS_MON_UP},
                {"lights_mon_down",   K_LIGHTS_MON_DOWN},
                {"lights_kbd_toggle", K_LIGHTS_KBD_TOGGLE},
                {"lights_kbd_up",     K_LIGHTS_KBD_UP},
                {"lights_kbd_down",   K_LIGHTS_KBD_DOWN},
                {NULL,                K_NOT_A_KEY} /* end marker */
        };

