name: release

on:
  release:
    types: [published]

jobs:
  win32:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Restore pkg cache
        id: cache-pkg
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: ~/.pkg-cache
          key: ${{ runner.os }}-pkg-18
      - name: Build
        run: yarn build:win32

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./hotkey-hub.exe
          asset_name: hotkey-hub.exe
          asset_content_type: application/vnd.microsoft.portable-executable
  docs:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Generate readme
        run: yarn schema:doc
      - name: Generate json schema
        run: yarn schema:json

      - name: Upload README
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./CONFIG.md
          asset_name: CONFIG.md
          asset_content_type: text/markdown
      - name: Upload json schema
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./json-schema.json
          asset_name: json-schema.json
          asset_content_type: application/json
      - name: Upload macros json schema
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./macros-schema.json
          asset_name: macros-schema.json
          asset_content_type: application/json

  linux:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies  # TODO cache
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev libxtst-dev libxcb-ewmh-dev libxcb1-dev cmake g++ make

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Restore pkg cache
        id: cache-pkg
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: ~/.pkg-cache
          key: ${{ runner.os }}-pkg-18
      - name: Build
        run: yarn build:linux

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./hotkey-hub.elf
          asset_name: hotkey-hub.elf
          asset_content_type: application/x-executable

  aur:
    needs: [linux, docs]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy PKGBUILD and related files
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=$(jq -r '.version' package.json)
          sed -i "s/^pkgver=.*/pkgver=${VERSION}/" ./packages/arch/PKGBUILD
          sed -i "s/^tag=.*/tag=${TAG}/" ./packages/arch/PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: hotkey-hub
          pkgbuild: ./packages/arch/PKGBUILD
          assets: |
            ./packages/arch/hotkey-hub.install
            ./packages/hotkey-hub.service
          commit_username: "GitHub Actions Bot"
          updpkgsums: "true"
          commit_email: "actions@github.com"
          ssh_private_key: ${{ secrets.PK_ARCH }}
          push_timeout: 1m
  deb:
    runs-on: ubuntu-22.04
    needs: [linux, docs]
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Prepare package
        env:
          DEBEMAIL: "deathangel908@gmail.com"
          DEBFULLNAME: "Andrew Koidan"
        run: |
          url="https://github.com/akoidan/hotkey-hub"
          tag="${{ github.event.release.tag_name }}"

                  
          wget -q "${url}/releases/download/${tag}/hotkey-hub.elf"
          wget -q "${url}/releases/download/${tag}/CONFIG.md"
          wget -q "${url}/releases/download/${tag}/json-schema.json"
          wget -q "${url}/releases/download/${tag}/macros-schema.json"
  
          VERSION=$(jq -r '.version' ./package.json)
          rootdir=$(pwd)
          srcdir="${rootdir}/packages/debian"
          pkgdir="${srcdir}/hotkey-hub"
          sed -i "s/^Version:.*/Version: ${VERSION}/" "${srcdir}/control"
          install -D -m 644 "${srcdir}/control" "${pkgdir}/DEBIAN/control"
          install -D -m 755 "${rootdir}/hotkey-hub.elf" "${pkgdir}/usr/bin/hotkey-hub"
          install -D -m 644 "${rootdir}/CONFIG.md" "${pkgdir}/usr/share/hotkey-hub/CONFIG.md"
          install -D -m 644 "${rootdir}/json-schema.json" "${pkgdir}/usr/share/hotkey-hub/json-schema.json"
          install -D -m 644 "${rootdir}/macros-schema.json" "${pkgdir}/usr/share/hotkey-hub/macros-schema.json"
          install -D -m 644 "${rootdir}/packages/hotkey-hub.service" "${pkgdir}/usr/lib/systemd/user/hotkey-hub.service"
          
          cd "$srcdir"
          dpkg-deb --build hotkey-hub hotkey-hub-amd64.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: packages/debian/hotkey-hub-amd64.deb
          asset_name: hotkey-hub.deb
          asset_content_type: application/vnd.debian.binary-package